services:
  db:
    image: mariadb:10.11
    container_name: crm_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - crm-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  backend:
    build: ./backend
    container_name: crm_backend
    restart: unless-stopped
    ports:
      - "6005:8000"
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - backend_uploads:/app/uploads
    networks:
      - crm-network

  frontend:
    build: ./frontend
    container_name: crm_frontend
    restart: unless-stopped
    ports:
      - "85:80"   
    environment:
      - REACT_APP_API_URL=http://10.87.0.59:6005/api
    depends_on:
      - backend
    networks:
      - crm-network

  bot:
    build: ./bot
    container_name: crm_bot
    restart: unless-stopped
    environment:
      - MAX_BOT_TOKEN=${MAX_BOT_TOKEN}
      - CRM_API_URL=http://backend:8000/api/messages
    env_file:
      - ./bot/.env
    depends_on:
      - backend
    networks:
      - crm-network

networks:
  crm-network:
    driver: bridge

volumes:
  db_data:
  backend_uploads:    # ← ДОБАВЛЕНО